server:
  port: 9999

demo: qwer

spring:
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/ygt?useSSL=false
      username: root
      password: 123123
    secondary:
      jdbc-url: jdbc:dm://localhost:5236/CLOUD
      username: CLOUD
      password: 123123123
      driver-class-name: dm.jdbc.driver.DmDriver
  jpa:
#    database: mysql
#    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: com.lurenjia.manydataresources.datasources.MySQLUpperCaseStrategy